# testing

# home
GET http://localhost:3000

### getAll
GET http://localhost:3000/games 
### get single
GET http://localhost:3000/games/6a0c6dc429e0c632d66a6ba7
###
GET http://localhost:3000/games/6a0c76417c0b7b2748b1c5e6